/**
 * Landings for the OpenAI image models: GPT Image 2.5 Flare, GPT Image 2.5
 * Sunburst and GPT Image 2.
 *
 * Format claims follow the registry: all three expose the same three fixed
 * sizes (square, landscape, portrait) and four quality levels — not the ten
 * aspect ratios the Google models offer. Every render on the Sunburst landing
 * is an edit result: the prompt in the caption is the edit instruction, and
 * the base photo it was applied to was itself generated by Sunburst.
 */

import { buildChips, buildImageSteps, sharedMediaFaq } from "./media-shared";
import {
  FLUX_SLUG,
  GPT_IMAGE_25_FLARE_SLUG,
  GPT_IMAGE_25_SUNBURST_SLUG,
  GPT_IMAGE_SLUG,
  NANO_BANANA_PRO_SLUG,
  NANO_BANANA_SLUG,
  SEEDREAM_45_SLUG,
  SOL_SLUG,
  vpnBenefit,
} from "./shared";
import type { LandingBenefit, LandingFaqItem, ModelLanding } from "./types";

const formatsBenefit: LandingBenefit = {
  icon: "ratio",
  title: "Три формата, четыре уровня качества",
  text: "Квадрат, альбомная и портретная ориентация плюс выбор качества — от быстрого черновика до финального кадра.",
};

const formatsFaq: LandingFaqItem = {
  question: "Какие форматы изображений доступны?",
  answer:
    "Три ориентации: квадрат, альбомная и портретная. Плюс выбор качества — от низкого для быстрых черновиков до высокого для финального кадра.",
};

const editOwnPhotoFaq: LandingFaqItem = {
  question: "Можно ли отредактировать своё фото?",
  answer:
    "Да. Прикрепите изображение в чат и опишите словами, что изменить. Модель вернёт новую версию, а исходник останется в истории диалога.",
};

const flareVsSunburstFaq: LandingFaqItem = {
  question: "Чем Flare отличается от Sunburst?",
  answer:
    "Обе модели — поколение GPT Image 2.5 от OpenAI с одинаковой ценой. Flare заточена под быструю повседневную генерацию с нуля, Sunburst — под точное редактирование готовых изображений. Обе умеют и то и другое, так что выбирайте по основной задаче.",
};

export const openaiImageLandings: ModelLanding[] = [
  {
    kind: "image",
    slug: GPT_IMAGE_25_FLARE_SLUG,
    modelId: "gpt-image-2.5-flare",
    name: "GPT Image 2.5 Flare",
    vendor: "OpenAI",
    accent: "warm",
    badge: "OpenAI · Быстрая генерация · Изображения",
    h1Top: "GPT Image 2.5 Flare\u00A0—",
    h1Gradient: "быстрая нейросеть OpenAI для картинок",
    sub: "Новая модель OpenAI для повседневной генерации уже в GIPITI — посты, карточки товаров и иллюстрации по описанию за секунды, плюс правки готовых картинок. Без VPN, на русском, с оплатой российскими картами. Дарим 200 ₽ каждому новому пользователю.",
    ctaMain: "Попробовать Flare",
    metaTitle:
      "GPT Image 2.5 Flare — быстрая генерация изображений от OpenAI | GIPITI",
    metaDescription:
      "GPT Image 2.5 Flare в GIPITI — новая модель OpenAI для быстрой повседневной генерации изображений по описанию на русском. Без VPN, оплата российскими картами. Дарим 200 ₽ новым пользователям.",
    heroMedia: {
      userMessage:
        "Осенний пикник на пледе, вид сверху: термос, круассаны, яблоки и книга, тёплый дневной свет, альбомный формат",
      aiIntro:
        "Готово. Могу поменять свет, добавить предметов или сделать вертикальную версию:",
      aspect: "3:2",
      resultCaption: "Осенний пикник сверху · термос, круассаны, книга",
      resultMeta: "Качество high · альбомный формат",
      sample: {
        src: "/images/model-landings/gpt-image-2-5-flare/autumn-picnic.webp",
        alt: "Вид сверху на осенний пикник на клетчатом пледе: термос, круассаны, яблоки, книга и кружка чая — изображение, созданное GPT Image 2.5 Flare в GIPITI",
        width: 1280,
        height: 853,
      },
    },
    benefits: [
      {
        icon: "zap",
        title: "Быстро — удобно перебирать варианты",
        text: "Flare рассчитана на повседневные задачи: результат за секунды, а не минуты. Сгенерируйте пять вариантов и выберите лучший, не дожидаясь каждого.",
      },
      {
        icon: "image",
        title: "Качество, готовое к публикации",
        text: "Аккуратная геометрия, свет и материалы, за которые ценят модели OpenAI, — в формате, который можно сразу ставить в пост или карточку товара.",
      },
      {
        icon: "wand",
        title: "Правки готовых картинок",
        text: "Прикрепите изображение и опишите, что поменять — фон, объект, цвет. Для тонких правок с сохранением каждой детали есть Sunburst.",
      },
      vpnBenefit,
    ],
    steps: buildImageSteps("GPT Image 2.5 Flare"),
    audience: [
      {
        title: "SMM и контент-команды",
        text: "Визуалы для постов и сторис в одном стиле — сегодня, а не когда освободится дизайнер.",
        userMessage:
          "Квадратная картинка для поста: матча-латте в белой чашке на пастельно-жёлтом фоне, жёсткие тени",
        aiReply: "**Пост** · матча-латте, пастельно-жёлтый фон",
        sample: {
          src: "/images/model-landings/gpt-image-2-5-flare/matcha-post.webp",
          alt: "Матча-латте в белой керамической чашке на пастельно-жёлтом фоне с жёсткими тенями — визуал для соцсетей",
          width: 900,
          height: 900,
        },
      },
      {
        title: "Интернет-магазины",
        text: "Предметные кадры и карточки товара без студии и фотографа.",
        userMessage:
          "Белые беспроводные наушники в открытом кейсе на светло-сером подиуме, мягкий студийный свет",
        aiReply: "**Карточка товара** · наушники на подиуме",
        sample: {
          src: "/images/model-landings/gpt-image-2-5-flare/earbuds.webp",
          alt: "Белые беспроводные наушники в открытом зарядном кейсе на светло-сером подиуме при студийном свете",
          width: 900,
          height: 600,
        },
      },
      {
        title: "Блогеры и авторы",
        text: "Иллюстрации к статьям и рассылкам в узнаваемом стиле — по одному описанию.",
        userMessage:
          "Плоская векторная иллюстрация: девушка работает за ноутбуком у большого окна с растениями, тёплая палитра, вертикально",
        aiReply: "**Иллюстрация** · работа у окна, плоский стиль",
        sample: {
          src: "/images/model-landings/gpt-image-2-5-flare/blog-illustration.webp",
          alt: "Плоская векторная иллюстрация: девушка работает за ноутбуком у большого окна с комнатными растениями в тёплой палитре",
          width: 600,
          height: 900,
        },
      },
    ],
    faq: [
      {
        question: "Что такое GPT Image 2.5 Flare?",
        answer:
          "GPT Image 2.5 Flare — новая модель OpenAI для генерации изображений, оптимизированная под быструю повседневную работу. В GIPITI она доступна без VPN, с интерфейсом на русском языке и оплатой российскими картами.",
      },
      flareVsSunburstFaq,
      formatsFaq,
      ...sharedMediaFaq,
    ],
    otherModels: buildChips([
      {
        name: "GPT Image 2.5 Sunburst",
        tag: "Изображения",
        slug: GPT_IMAGE_25_SUNBURST_SLUG,
      },
      { name: "GPT Image 2", tag: "Изображения", slug: GPT_IMAGE_SLUG },
      { name: "Nano Banana", tag: "Изображения", slug: NANO_BANANA_SLUG },
      { name: "GPT-5.6 Sol", tag: "Текст", slug: SOL_SLUG },
    ]),
  },
  {
    kind: "image",
    slug: GPT_IMAGE_25_SUNBURST_SLUG,
    modelId: "gpt-image-2.5-sunburst",
    name: "GPT Image 2.5 Sunburst",
    vendor: "OpenAI",
    accent: "violet",
    badge: "OpenAI · Точное редактирование · Изображения",
    h1Top: "GPT Image 2.5 Sunburst\u00A0—",
    h1Gradient: "нейросеть OpenAI для правок изображений",
    sub: "Новая модель OpenAI с упором на редактирование уже в GIPITI — прикрепите фото, опишите правку словами и получите результат без потери остальной сцены. Генерирует с нуля тоже. Без VPN, на русском, с оплатой российскими картами. Дарим 200 ₽ каждому новому пользователю.",
    ctaMain: "Попробовать Sunburst",
    metaTitle:
      "GPT Image 2.5 Sunburst — точное редактирование изображений от OpenAI | GIPITI",
    metaDescription:
      "GPT Image 2.5 Sunburst в GIPITI — новая модель OpenAI для точного редактирования изображений по описанию на русском: фон, объекты, свет. Без VPN, оплата российскими картами. Дарим 200 ₽ новым пользователям.",
    heroMedia: {
      userMessage:
        "Убери прохожих с фона и сделай свет как на закате — велосипед и стену не трогай 📎 bike.jpg",
      aiIntro:
        "Готово — люди убраны, свет тёплый. Могу вернуть исходник или поправить ещё:",
      aspect: "3:2",
      resultCaption: "Велосипед у кирпичной стены · без прохожих, золотой час",
      resultMeta: "Редактирование · качество high · альбомный формат",
      sample: {
        src: "/images/model-landings/gpt-image-2-5-sunburst/bicycle-edit.webp",
        alt: "Красный велосипед у старой кирпичной стены на пустой улице в тёплом закатном свете — результат редактирования фото в GPT Image 2.5 Sunburst в GIPITI",
        width: 1280,
        height: 853,
      },
    },
    benefits: [
      {
        icon: "wand",
        title: "Точное редактирование",
        text: "Заменить фон, убрать лишнее, поменять свет — Sunburst меняет только то, о чём попросили, а лица, предметы и композицию сохраняет как в исходнике.",
      },
      {
        icon: "image",
        title: "Генерация с нуля тоже",
        text: "Нужна новая картинка, а не правка? Опишите сцену — модель нарисует её в том же качестве, что и GPT Image 2.5 Flare.",
      },
      formatsBenefit,
      vpnBenefit,
    ],
    steps: buildImageSteps(
      "GPT Image 2.5 Sunburst",
      "Прикрепите фото и напишите, что изменить, — или опишите новую картинку с нуля."
    ),
    audience: [
      {
        title: "Интернет-магазины",
        text: "Один товарный кадр — десятки сцен: перенесите продукт в интерьер или на улицу, не снимая заново.",
        userMessage:
          "Поставь этот рюкзак на скамейку в солнечном парке, сам рюкзак не меняй 📎 backpack.jpg",
        aiReply: "**Готово** · рюкзак на скамейке в парке",
        sample: {
          src: "/images/model-landings/gpt-image-2-5-sunburst/backpack-edit.webp",
          alt: "Коричневый кожаный рюкзак на деревянной скамейке в солнечном парке — товарное фото, перенесённое в новую сцену",
          width: 900,
          height: 600,
        },
      },
      {
        title: "Маркетологи",
        text: "Сезонные версии одного визуала: смените фон и свет под кампанию, оставив продукт нетронутым.",
        userMessage:
          "Замени фон на пляж на закате, бутылку и этикетку оставь как есть 📎 lemonade.jpg",
        aiReply: "**Летняя версия** · пляж на закате",
        sample: {
          src: "/images/model-landings/gpt-image-2-5-sunburst/lemonade-edit.webp",
          alt: "Стеклянная бутылка лимонада с долькой лимона на песке пляжа на закате — фон заменён, продукт сохранён",
          width: 900,
          height: 900,
        },
      },
      {
        title: "HR и личный бренд",
        text: "Деловое фото из любого снимка: уберите беспорядок на фоне и выровняйте свет.",
        userMessage:
          "Замени захламлённый офис на нейтральный студийный фон, меня не меняй 📎 photo.jpg",
        aiReply: "**Деловой портрет** · нейтральный студийный фон",
        sample: {
          src: "/images/model-landings/gpt-image-2-5-sunburst/portrait-edit.webp",
          alt: "Портрет улыбающегося мужчины в сером свитере на нейтральном светло-сером студийном фоне — фон заменён при редактировании",
          width: 600,
          height: 900,
        },
      },
    ],
    faq: [
      {
        question: "Что такое GPT Image 2.5 Sunburst?",
        answer:
          "GPT Image 2.5 Sunburst — новая модель OpenAI для генерации и редактирования изображений с упором на точные правки. В GIPITI она доступна без VPN, с интерфейсом на русском языке и оплатой российскими картами.",
      },
      {
        question: "Чем Sunburst отличается от Flare?",
        answer:
          "Обе модели — поколение GPT Image 2.5 от OpenAI с одинаковой ценой. Sunburst заточена под редактирование: точнее сохраняет исходник и меняет только то, о чём попросили. Flare — под быструю генерацию с нуля. Обе умеют и то и другое.",
      },
      editOwnPhotoFaq,
      ...sharedMediaFaq,
    ],
    otherModels: buildChips([
      {
        name: "GPT Image 2.5 Flare",
        tag: "Изображения",
        slug: GPT_IMAGE_25_FLARE_SLUG,
      },
      { name: "GPT Image 2", tag: "Изображения", slug: GPT_IMAGE_SLUG },
      {
        name: "Nano Banana Pro",
        tag: "Изображения",
        slug: NANO_BANANA_PRO_SLUG,
      },
      { name: "Flux 2 Max", tag: "Изображения", slug: FLUX_SLUG },
    ]),
  },
  {
    kind: "image",
    slug: GPT_IMAGE_SLUG,
    modelId: "gpt-image-2",
    name: "GPT Image 2",
    vendor: "OpenAI",
    accent: "emerald",
    badge: "OpenAI · Фотореализм и правки · Изображения",
    h1Top: "GPT Image 2 —",
    h1Gradient: "нейросеть OpenAI для изображений",
    sub: "Проверенная модель OpenAI для генерации изображений уже в GIPITI — фотореалистичные кадры по описанию и точное редактирование готовых картинок. Без VPN, на русском, с оплатой российскими картами. Дарим 200 ₽ каждому новому пользователю.",
    ctaMain: "Попробовать GPT Image 2",
    metaTitle: "GPT Image 2 — генерация изображений от OpenAI | GIPITI",
    metaDescription:
      "GPT Image 2 в GIPITI — фотореалистичная генерация и редактирование изображений по описанию на русском. Без VPN, оплата российскими картами. Дарим 200 ₽ новым пользователям.",
    heroMedia: {
      userMessage:
        "Фото рабочего стола сверху: ноутбук, блокнот и кофе, мягкий утренний свет, альбомная ориентация",
      aiIntro: "Готово. Могу поменять свет, ракурс или добавить деталей:",
      aspect: "3:2",
      resultCaption: "Рабочий стол сверху · ноутбук, блокнот, кофе",
      resultMeta: "Качество high · альбомный формат",
      sample: {
        src: "/images/model-landings/gpt-image-2/desk.webp",
        alt: "Вид сверху на рабочий стол: ноутбук, блокнот и чашка кофе в утреннем свете — изображение, созданное GPT Image 2 в GIPITI",
        width: 1280,
        height: 853,
      },
    },
    benefits: [
      {
        icon: "image",
        title: "Фотореалистичные кадры",
        text: "Предметная съёмка, интерьеры и портретные сцены — модель OpenAI известна аккуратной геометрией, светом и материалами.",
      },
      {
        icon: "wand",
        title: "Точное редактирование",
        text: "Прикрепите картинку и опишите правку — заменить объект, убрать лишнее, поменять фон. Остальная сцена останется нетронутой.",
      },
      formatsBenefit,
      vpnBenefit,
    ],
    steps: buildImageSteps("GPT Image 2"),
    audience: [
      {
        title: "Интернет-магазины",
        text: "Предметные кадры и карточки товара без студии и фотографа.",
        userMessage:
          "Покажи эти часы на мраморной поверхности с мягкой тенью 📎 watch.jpg",
        aiReply: "**Готово** · часы на мраморе, мягкая тень",
        sample: {
          src: "/images/model-landings/gpt-image-2/watch.webp",
          alt: "Золотые наручные часы на мраморной поверхности с мягкой тенью",
          width: 900,
          height: 600,
        },
      },
      {
        title: "Маркетологи",
        text: "Рекламные визуалы и баннеры под кампанию — в одном стиле и нужной ориентации.",
        userMessage:
          "Баннер для рассылки: летняя веранда кафе, тёплые тона, альбомный формат",
        aiReply: "**Баннер** · летняя веранда, тёплые тона",
        sample: {
          src: "/images/model-landings/gpt-image-2/terrace-banner.webp",
          alt: "Баннер для рассылки «Лето вкуснее на веранде»: летняя терраса кафе в тёплых тонах",
          width: 900,
          height: 600,
        },
      },
      {
        title: "Дизайнеры интерьеров",
        text: "Визуализация идей до ремонта: материалы, свет и расстановка мебели.",
        userMessage:
          "Кухня 12 м² в скандинавском стиле, дневной свет, вид от двери",
        aiReply: "**Кухня 12 м²** · скандинавский стиль, дневной свет",
        sample: {
          src: "/images/model-landings/gpt-image-2/scandic-kitchen.webp",
          alt: "Кухня в скандинавском стиле при дневном свете, вид от двери",
          width: 900,
          height: 600,
        },
      },
    ],
    faq: [
      {
        question: "Что такое GPT Image 2?",
        answer:
          "GPT Image 2 — модель OpenAI прошлого поколения для генерации и редактирования изображений. В GIPITI она доступна без VPN, с интерфейсом на русском языке и оплатой российскими картами.",
      },
      {
        question: "Чем GPT Image 2 отличается от GPT Image 2.5?",
        answer:
          "GPT Image 2.5 — следующее поколение в двух вариантах: Flare для быстрой повседневной генерации и Sunburst для точного редактирования, по той же цене. GPT Image 2 остаётся доступна в GIPITI — можно сравнить результаты на своей задаче.",
      },
      formatsFaq,
      editOwnPhotoFaq,
      ...sharedMediaFaq,
    ],
    otherModels: buildChips([
      {
        name: "GPT Image 2.5 Flare",
        tag: "Изображения",
        slug: GPT_IMAGE_25_FLARE_SLUG,
      },
      {
        name: "GPT Image 2.5 Sunburst",
        tag: "Изображения",
        slug: GPT_IMAGE_25_SUNBURST_SLUG,
      },
      { name: "Nano Banana", tag: "Изображения", slug: NANO_BANANA_SLUG },
      { name: "Seedream 4.5", tag: "Изображения", slug: SEEDREAM_45_SLUG },
    ]),
  },
];
