import {
  absoluteUrl,
  CONTENT_SIGNALS,
  SITE_ORIGIN,
} from "@/lib/agent-discovery/constants";

/**
 * `robots.txt` is generated by a route handler rather than the `app/robots.ts`
 * metadata convention because `MetadataRoute.Robots` can only express
 * `Allow`/`Disallow`/`Crawl-delay`, and we need the `Content-Signal` directive
 * (contentsignals.org) alongside them.
 */

const DISALLOWED_PATHS = [
  "/api/",
  "/chat/",
  "/subscription",
  "/blog/preview",
] as const;

const PREAMBLE = [
  "# Content signals declare how this site's content may be reused.",
  "# They express a preference, not a licence grant, and do not replace the",
  "# Disallow rules below. See https://contentsignals.org for the full text.",
  "#",
  "#   search    = yes  — indexing for search results is allowed",
  "#   ai-input  = yes  — AI assistants may retrieve pages to answer questions",
  "#   ai-train  = no   — content may not be used to train models",
];

const robotsTxt = [
  ...PREAMBLE,
  "",
  "User-agent: *",
  `Content-Signal: ${CONTENT_SIGNALS}`,
  "Allow: /",
  ...DISALLOWED_PATHS.map((path) => `Disallow: ${path}`),
  "",
  `Sitemap: ${absoluteUrl("/sitemap.xml")}`,
  "",
  "# Machine-readable discovery entrypoints, also advertised as RFC 8288 Link",
  "# headers on every page:",
  `#   ${absoluteUrl("/.well-known/api-catalog")}`,
  `#   ${absoluteUrl("/.well-known/agent-skills/index.json")}`,
  `#   ${absoluteUrl("/openapi.json")}`,
  "#",
  `# Public pages also answer 'Accept: text/markdown' with Markdown: ${SITE_ORIGIN}`,
  "",
].join("\n");

export function GET(): Response {
  return new Response(robotsTxt, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=86400",
    },
  });
}
